python3  VIOLENCE_DETECTION/main_ag-cnn.py \
--lib pytorch \
--modelType resnet50 \
--inputSize 224 \
--dataset hockey \
--lr 0.01 \
--useValSplit False \
--numEpochs 2 \
--numWorkers 4 \
--batchSize 8 \
--freezeConvLayers True \
--joinType maxTempPool \
--videoSegmentLength 30 \
--numDynamicImagesPerVideo 1 \
--positionSegment begin \
--skipInitialFrames 0 \
--overlapping 0 \
--frameSkip 0 \
--saveCheckpoint False \
--splitType cross-val \
--patience 10 \
# --pretrained /media/david/datos/PAPERS-SOURCE_CODE/violencedetection2/MODELS/pretrained/c3d-pretrained.pth
# --pretrained https://download.openmmlab.com/mmaction/recognition/c3d/c3d_sports1m_pretrain_20201016-dcc47ddc.pth
# --transferModel RESULTS/HOCKEY/checkpoints/DYN_Stream-_dataset=[hockey]_model=resnet50_numEpochs=25_freezeConvLayers=True_numDynamicImages=1_segmentLength=30_frameSkip=0_skipInitialFrames=0_overlap=0.0_joinType=maxTempPool_useKeyframes=None_windowLen=0-fold=1.pt
# --useKeyframes blur-max \
# --windowLen 10
